"""Fix SQLite datetime functions

Revision ID: f9d1212ce47a
Revises: 001
Create Date: 2025-07-18 19:46:17.078360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f9d1212ce47a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_scores', sa.Column('score_metadata', sa.JSON(), nullable=True))
    op.drop_column('candidate_scores', 'metadata')
    op.add_column('match_history', sa.Column('action_metadata', sa.JSON(), nullable=True))
    op.drop_column('match_history', 'metadata')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.add_column('match_history', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('match_history', 'action_metadata')
    op.add_column('candidate_scores', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('candidate_scores', 'score_metadata')
    # ### end Alembic commands ###
